const token=location.hash.slice(1); history.replaceState(null,"",location.pathname);
const headers={Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
const profiles=document.querySelector("#profiles"), notice=document.querySelector("#notice"), dialog=document.querySelector("#editor"), form=document.querySelector("#form"), errors=document.querySelector("#errors");
async function api(path,options={}){const response=await fetch(path,{...options,headers});if(!response.ok){const body=await response.json().catch(()=>({message:response.statusText}));throw body}return response.status===204?null:response.json()}
function escapeText(value){const node=document.createElement("span");node.textContent=value;return node.innerHTML}
async function load(){try{const items=await api("/api/v1/profiles");profiles.innerHTML=items.length?items.map(p=>`<article><div><h2>${escapeText(p.name)}</h2><p>${escapeText(p.region.country_code)} · ${escapeText(p.region.timezone)} · ${escapeText(p.hardware.cpu_class)} · ${escapeText(p.hardware.gpu_class)}</p></div><div><button data-start="${p.id}">Запустить</button><button class="secondary" data-edit="${p.id}">Изменить</button></div></article>`).join(""):"<div class=empty>Создайте первый изолированный профиль.</div>"}catch(e){notice.textContent=e.message||"API недоступен: откройте ссылку, показанную control service."}}
function defaults(){return{id:crypto.randomUUID(),revision:0,name:"",region:{country_code:"DE",timezone:"Europe/Berlin",locale:"de-DE",languages:["de-DE","de"],latitude:null,longitude:null},hardware:{architecture:"x86_64",cpu_class:"intel-8c-v1",logical_cores:8,memory_gib:16,gpu_class:"intel-iris-xe-v1"},proxy:null}}
function show(p){for(const [key,value] of Object.entries({id:p.id,revision:p.revision,name:p.name,country_code:p.region.country_code,timezone:p.region.timezone,locale:p.region.locale,languages:p.region.languages.join(","),cpu_class:p.hardware.cpu_class,logical_cores:p.hardware.logical_cores,memory_gib:p.hardware.memory_gib,gpu_class:p.hardware.gpu_class,proxy_scheme:p.proxy?.scheme||"",proxy_host:p.proxy?.host||"",proxy_port:p.proxy?.port||""}))form.elements[key].value=value;errors.textContent="";dialog.showModal()}
document.querySelector("#new").onclick=()=>show(defaults());document.querySelector("#cancel").onclick=()=>dialog.close();
profiles.onclick=async event=>{const edit=event.target.dataset.edit,start=event.target.dataset.start;try{if(edit)show(await api(`/api/v1/profiles/${edit}`));if(start){await api(`/api/v1/profiles/${start}/start`,{method:"POST"});notice.textContent="Браузер запущен."}}catch(e){notice.textContent=e.message}}
form.onsubmit=async event=>{event.preventDefault();const d=new FormData(form),scheme=d.get("proxy_scheme"),p={id:d.get("id"),revision:Number(d.get("revision")),name:d.get("name"),region:{country_code:d.get("country_code").toUpperCase(),timezone:d.get("timezone"),locale:d.get("locale"),languages:d.get("languages").split(",").map(v=>v.trim()).filter(Boolean),latitude:null,longitude:null},hardware:{architecture:"x86_64",cpu_class:d.get("cpu_class"),logical_cores:Number(d.get("logical_cores")),memory_gib:Number(d.get("memory_gib")),gpu_class:d.get("gpu_class")},proxy:scheme?{scheme,host:d.get("proxy_host"),port:Number(d.get("proxy_port")),resolve_dns_through_proxy:scheme==="socks5"}:null};try{await api(`/api/v1/profiles${p.revision?`/${p.id}`:""}`,{method:p.revision?"PUT":"POST",body:JSON.stringify(p)});dialog.close();await load()}catch(e){errors.textContent=(e.issues||[]).map(v=>`${v.path}: ${v.message}`).join("; ")||e.message}}
load();
